PNDA-4536 Kafka data dirs to be configurable in pnda_env.yaml
pndaproject/pnda-cli pull request #141
Opened 2018-06-27 16:24 UTC by SivaMaplelabs

Analysis:
Kafka data dirs to be configurable in pnda_env.yaml

Solution:
Added DATA_DIRS setting in pnda-env.yaml to set the data_dirs in the pillar
Added DEVICE_ROOT setting in pnda-env.yaml to set the disks in the volume-config.yaml

Tested:
RHEL HDP PICO
RHEL HDP STANDARD
RHEL HDP PRODUCTION

2018-07-02 13:24 UTC, jgarnier requested changes

2018-07-02 13:24 UTC, jgarnier commented on bootstrap-scripts/production/volume-config.yaml
> +  kafka: kafka
why introducing a new type on volume configuration for production which is the same configuration of generic?

2018-07-02 14:00 UTC, jeclarke commented on pnda_env_example.yaml
> +  # - /mnt/kafka-logs
take out the commented line

2018-07-02 14:04 UTC, jeclarke requested changes

2018-07-02 14:04 UTC, jeclarke commented on pnda_env_example.yaml
> +kafka:
rename DATA_DIRS and DEVICE_ROOT to KAFKA_DATA_DIRS and KAFKA_DEVICE_ROOT, as it stands DEVICE_ROOT will clash the one used under the datanode section. I will also create a JIRA to rename the datanode settings to be more specific too.

2018-07-04 04:54 UTC, SivaMaplelabs commented on bootstrap-scripts/production/volume-config.yaml
> +  kafka: kafka
Have introduced a new type to make 'KAFKA_DEVICE_ROOT' configurable through pnda_env.yaml as like datanode DEVICE_ROOT(https://issues.pnda.io/browse/PNDA-4075).

2018-07-04 04:57 UTC, SivaMaplelabs commented
@jeclarke Have addressed your comments.

2018-07-04 10:01 UTC, jeclarke approved these changes

2018-07-04 13:29 UTC, jgarnier commented on bootstrap-scripts/production/volume-config.yaml
> +  kafka: kafka
ok good then now as this is no more the same as generic

2018-07-04 13:32 UTC, jgarnier approved these changes

2018-07-04 14:16 UTC, merged