PNDA-4876 Introduce 'security material missing' check at config check
pndaproject/pnda-cli pull request #170
Opened 2018-08-23 13:54 UTC by SivaMaplelabs

PNDA-4876

2018-08-23 17:50 UTC, stephanesan requested changes

2018-08-23 17:50 UTC, stephanesan commented on cli/backend_base.py
> +        self._ensure_certs()
Can you just rename the function to have consistency with the function names above and something more relevant now. Something like: _check_security_material()

2018-08-24 04:34 UTC, SivaMaplelabs commented
@stephanesan Done. Thanks

2018-08-24 08:09 UTC, stephanesan commented
:+1:

2018-08-24 08:09 UTC, merged