Creation time improvements for large clusters when there is no bastion
pndaproject/pnda-cli pull request #39
Opened 2017-12-08 16:28 UTC by jeclarke

Run host operations simultaneously. The number of operations to execute
simultaneously is  controlled by a new pnda-env.yaml config
`cli:MAX_SIMULATANEOUS_OUTBOUND_CONNECTIONS`. This setting is defaulted
to 100, if a cluster with more than 100 nodes is being created the
operator can increase this at their discretion.

When there is a bastion, continue to wait 2 seconds between starting
each operation so the bastion does not get overloaded with inbound
connections.

This means the effective wait time when using a bastion still scales
with the number of nodes (number of nodes*4 seconds) and when not using
a bastion it does not increase with the number of nodes assuming
MAX_SIMULATANEOUS_OUTBOUND_CONNECTIONS can be set higher than the
number of nodes in the cluster. If it cannot be set higher then the time will scale with the number of batches the operations must be run in to keep the number of connections below this figure.

PNDA-3553

2017-12-10 16:01 UTC, trsmith2 requested changes
Let's look at a threadless approach to multitasking

2017-12-10 23:25 UTC, jeclarke commented
I agree - that is something on my mind too. I think that will require  a change to a python ssh library to avoid calling ssh and scp with subprocess. This is a possibility: http://asyncssh.readthedocs.io/en/latest/but I’ve not used it before.

2017-12-11 07:26 UTC, trsmith2 commented
I'll merge this - since we already use threads this **is** a safer & more performant implementation - and let's make one of the next refactorings in this repository a removal of threads altogether in favour of an NIO approach

2017-12-11 07:26 UTC, trsmith2 approved these changes

2017-12-11 07:27 UTC, merged